apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: library-system
    app.kubernetes.io/managed-by: helm
data:
  setup.sql: |
    CREATE ROLE {{ .Values.user.name }} WITH PASSWORD '{{ .Values.user.password }}';
    ALTER ROLE {{ .Values.user.name }} WITH LOGIN;

    CREATE DATABASE libraries;
    GRANT ALL PRIVILEGES ON DATABASE libraries TO {{ .Values.user.name }};

    CREATE DATABASE ratings;
    GRANT ALL PRIVILEGES ON DATABASE ratings TO {{ .Values.user.name }};

    CREATE DATABASE reservations;
    GRANT ALL PRIVILEGES ON DATABASE reservations TO {{ .Values.user.name }};
